import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist

# Download required NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Set the maximum number of sentences to include in the summary
MAX_SENTENCES = 3

# # Read in the text to be summarized
# with open('input_text.txt', 'r') as f:
#     text = f.read()

text = """Bluetooth technology was designed originally for cable replacement and short-range ad hoc connectivity. It operates
in the 2.4 GHz ISM frequency band exploiting 79 RF channels of 1 MHz width each, thus defining a maximum
transmission rate of 1 Mbps. The building block of a Bluetooth Personal Area Network is represented by the
Piconet, i.e. a set of up to eight devices sharing the same physical channel. One of these devices assumes the
role of Master (in charge of establishing and managing the communication), and all the others play the role of
Slave. These devices are synchronized on the same clock and adopt the same frequency hopping scheme based
on a Time Division Multiplexing technique that divides the channel in 625 μsec slots. Transmissions occur in
packets that occupy an odd number of slots (up to five) and are transmitted on different hop frequencies with a
maximum hop frequency rate of 1600 hops/sec. The communication protocol is divided mainly to in two phases:
the discovery phase in which the master device discovers up to seven active slaves in its transmission range and
exchanges data necessary for synchronization, and the data exchange. Therefore, data can be transferred between
the master and one slave; then the master switches from one slave to another in a round-robin fashion. Two
types of communication link are defined: Asynchronous Connection-Less (ACL), an asymmetric point-to-point
6 These results are obtained by considering a crystal tolerance of better than 25 ppm defined as the initial deviation of the
crystal or oscillator frequency as compared to the absolute at 25C.Wearable Computing and Sensor Systems for Healthcare
127
link between the master and the active slaves using retransmissions to guarantee data integrity; Synchronous
Connection-Oriented (SCO), a symmetric point-to-point connection between the master and a specific slave at a
regular time interval. The latter is designed mainly for supporting real-time traffic (e.g. voice), while the former is
dedicated to data communications as necessary for healthcare applications. Evaluating end-to-end delays, packet
loss at the receiving node, and efficiency in terms of the ratio between the successful received data packets and the
number of data packets generated by the application layer for that receiver, the simulation results in [51] show that
Bluetooth technology presents mainly scalability issues related to the limited number of sensors for the collecting
device (max seven slaves for each Piconet) and packet loss problems in case of multiple piconets for the same
receiver (master) due to interferences. Even though power consumption during transmission is quite low, the need
for Bluetooth devices to be active continuously for device discovery or join new piconets implies higher power
requirements. Nevertheless, Bluetooth is one of the most frequently used technologies in Health BAN, probably
because it is integrated natively in a high number of mobile devices, while it is not easy to find a smartphone
equipped with a ZigBee wireless card. 7 In the last few years, Bluetooth SIG has worked on a new standard aimed at
reducing the power consumption of Bluetooth devices, as well as meeting medical application requirements. This
standard is called Bluetooth Low Energy and it mainly redesigns the communication protocol while maintaining
its basic features.
8.7.3
Bluetooth Low Energy
Bluetooth Low Energy (LE) wireless technology represents the main feature of the latest Bluetooth Core specifi-
cation (v.4.0) released in December 2009 [54]. It extends the applicability of Bluetooth into low power and low
cost applications introducing important features that heated up the competition with ZigBee in the development
of efficient and reliable Health BANs. It inherits from the standard Bluetooth specification the operating spectrum
(2.4 GHz) and the basic structure of the communication protocol, but it implements a completely new lightweight
Link Layer that provides ultra-low power idle mode operation, simple and fast device discovery and reliable and
secure point-to-multipoint data transfers. One of the main disadvantages of classical Bluetooth is the time required
by devices to discover and synchronize themselves on the same channel, due to the frequency hopping procedure
and, consequently, the energy consumed during its execution. In Bluetooth-LE the same procedure is maintained
but the number of channels is reduced from 32 to only three. These channels are used for advertising the presence
of slaves available to communicate with the master, so that the master node only has to scan three channels to open
a connection and start to exchange messages. This procedure takes few msec (less than 3 msec), thus allowing the
devices to further save power by staying asleep most of the time and waking up quickly in case of events. The
reduction of channels in frequency hopping is also due to a larger modulation index implemented in Bluetooth-LE,
increasing the frequency spectrum, and the definition of low-energy consumption filters that require the separation
of channels of 2 MHz instead of 1 MHz. In addition, the hopping sequence is simplified in a wrap around sequence
instead of pseudo-random, and a functionality similar to the Adaptive Frequency Hopping is maintained in order
to detect channels used by other devices and technologies (e.g. WiFi).
Regarding data transfer, Bluetooth-LE inherits 1 Mbps data rate from classical Bluetooth and, in order to provide
an ultra-low power transmission, it utilizes short data packets with a dynamic length (8 octects minimum up to
27 octects maximum). This feature, in addition to the fast establishment of a connection, makes this technology
especially effective in situations of burst data transfers. In fact, the specification declares that a device can wake
up, connect, send some application data and then disconnect again within 3 msec. In this way, the lowest amount
of energy is used, maintaining the fastest transmission of event-based data.
Regarding the hardware characteristics of these devices, there exist two types of implementation: single-mode and
dual-mode. Single-mode is pure low-energy implementation providing a dedicated controller in highly integrated
and compact devices. By contrast, in dual-mode implementation, the LE functionality is integrated into an existing
classic Bluetooth controller, allowing the coexistence of these two technologies in the same device, even using
the same radio and antenna, resulting in a substantial enhancement of current chips by the new low energy stack
with a minimal cost increase. The dual-mode is designed to enable fast adoption of LE functionality in classic
Bluetooth applications, such as mobile phones and PDA, through a low cost modification, removing the need to
add another radio. Several major mobile phone vendors have indicated that they will adopt dual mode devices in
7 Mini- and Micro-SD ZigBee cards have recently been launched on the market by a Taiwanese company [64], but the firmware
and the related software support is still limited to only a few operating systems.128
Pervasive Computing and Networking
their upcoming phones [55]. Owing to the double nature of Bluetooth-LE devices, they can generate two types of
network topology: star and star-bus. The star topology is considered to be mainly that among single-mode devices
only, in which one device assumes the role of Hub and the others the role of Nodes (comparable to the Bluetooth
piconet concept, although here there is no a theoretical limit on the number of active slaves). By contrast, the
star-bus topology can include both single- and dual-mode devices and even classical Bluetooth devices. Generally,
dual-mode devices act as Hubs and the single-mode as Nodes, establishing Bluetooth-LE connections between a
Hub and a Node, while the backbone connection between different Hubs is a classic Bluetooth connection. For
this reason, in this topology the role of Hub can also be assumed by a classical Bluetooth device connected to
dual-mode devices. An example of this topology can be represented by a mobile phone equipped with a dual-mode
device that maintains LE connections to single-mode wearable sensors and, at the same time, a classic Bluetooth
connection to other standard devices.
This technology fits well with the features and functionalities of pervasive healthcare systems in the case of low
data rate requirements. However, where it is necessary to obtain higher data rates we have to take into consideration
other technologies such as Ultra Wide Band and 60 GHz millimeter-wave [56], but they are generally used for
hospital-centered systems and not for Health BAN communications."""

# Tokenize the text into sentences and words
sentences = sent_tokenize(text)
words = word_tokenize(text)

# Remove stop words
stop_words = set(stopwords.words('english'))
words = [word for word in words if word.casefold() not in stop_words]

# Calculate the frequency of each word
word_freq = FreqDist(words)

# Calculate the score for each sentence by adding up the frequencies of its constituent words
sent_scores = {}
for i, sentence in enumerate(sentences):
    for word in word_tokenize(sentence.lower()):
        if word in word_freq:
            if i not in sent_scores:
                sent_scores[i] = word_freq[word]
            else:
                sent_scores[i] += word_freq[word]

# Select the top N sentences with the highest scores
top_sentences = sorted(sent_scores, key=sent_scores.get, reverse=True)[:MAX_SENTENCES]

# Sort the top sentences in their original order
summary = [sentences[i] for i in sorted(top_sentences)]

# Output the summary
print('\n'.join(summary))
